
import { Inter } from 'next/font/google'
import  Header  from '../components/Header'
import Footer from '../components/Footer'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Open Films',
  description: 'Generated by create next app',
}

export default function Layout({ children }) {
  return (
    <> 
        <Header/>
        <div className='container mx-auto'>
          {children}
        </div>
        <Footer/>
    </>

  )
}
